name: Weekly Intern Update
description: Weekly status update for interns (Java / Python)
title: "Weekly Update - <Intern Name> - Week <Number>"
labels:
  - weekly-update
body:
  - type: markdown
    attributes:
      value: |
        ## Weekly Update Template

        Please fill in all sections below. Update this issue daily.

  - type: input
    id: intern_name
    attributes:
      label: Intern Name
      placeholder: Enter your full name
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain
      options:
        - Java
        - Python
    validations:
      required: true

  - type: input
    id: project_name
    attributes:
      label: Project Name
      placeholder: Enter project name
    validations:
      required: true

  - type: textarea
    id: week_plan
    attributes:
      label: Week Plan
      description: List all GitHub issues planned for this week
      value: |
        - [ ] https://github.com/org/repo/issues/123
        - [ ] https://github.com/org/repo/issues/124
    validations:
      required: true

  - type: textarea
    id: daily_updates
    attributes:
      label: Daily Updates
      description: Update this section daily
      value: |
        ### Date: YYYY-MM-DD
        - [ ] Issue Link
          - Work done:
          - Status:
          - Notes:
    validations:
      required: true

  - type: textarea
    id: prs
    attributes:
      label: Pull Requests
      description: Add PR links if any
      value: |
        - PR Link:
          Status:
    validations:
      required: false

  - type: textarea
    id: blockers
    attributes:
      label: Blockers / Risks
      description: Mention blockers if any
      placeholder: None
    validations:
      required: false

  - type: textarea
    id: learnings
    attributes:
      label: Learnings This Week
      placeholder: What did you learn this week?
    validations:
      required: false

  - type: textarea
    id: next_week
    attributes:
      label: Plan for Next Week
      placeholder: High-level plan for next week
    validations:
      required: false
