# Weekly Update – <Intern Name>
**Domain:** Java / Python  
**Project:** <Project Name>  
**Week:** <Start Date> – <End Date>  
**Mentor:** <Mentor Name>  

---

## 🔹 Week Plan
(List all issues planned for this week)

- [ ] <GitHub Issue Link> – <Short description>
- [ ] <GitHub Issue Link> – <Short description>
- [ ] <GitHub Issue Link> – <Short description>

---

## 🔹 Daily Updates

### **<Date>**
- [ ] <GitHub Issue Link>  
  - Work done: <what was worked on>
  - Status: In progress / Completed / Blocked
  - Notes (optional): <any challenges / discussions / PR info>

---

### **<Date>**
- [ ] <GitHub Issue Link>  
  - Work done:
  - Status:
  - Notes:

---

### **<Date>**
- [ ] <GitHub Issue Link>  
  - Work done:
  - Status:
  - Notes:

---

## 🔹 Pull Requests (if any)
- PR Link: <GitHub PR URL>  
  - Description: <what the PR covers>
  - Status: Open / Merged / Changes Requested

---

## 🔹 Blockers / Risks
- <Any technical, dependency, or access issues>

---

## 🔹 Learnings This Week
- <New concepts, tools, frameworks, or practices learned>

---

## 🔹 Plan for Next Week
- <High-level plan or issues to be picked up next>
